name: React Project Artifact
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Node Js Environment
              uses: actions/setup-node@v6

            - name: Install Dependencies
              run: npm install
#create build
            - name: Build React Appp
              run: npm run build

            - name: Upload build artifacts
              use: actions/upload-artifact@v4
              with: 
              name: react-build
              path: dist

            